apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-hml
  namespace: igreja-hml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-hml
  template:
    metadata:
      labels:
        app: backend-hml
    spec:
      imagePullSecrets:
        - name: ecr-pull-secret   # ğŸ‘ˆ LINHA CRÃTICA
      containers:
        - name: backend
          image: 112367726434.dkr.ecr.us-east-1.amazonaws.com/igreja-backend:hml
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
