apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-hml
  namespace: igreja-hml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-hml
  template:
    metadata:
      labels:
        app: backend-hml
    spec:
      containers:
        - name: backend
          image: 112367726434.dkr.ecr.us-east-1.amazonaws.com/igreja-backend:dev
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: igreja
            - name: DB_USER
              value: igreja
            - name: DB_PASSWORD
              value: igreja123
          ports:
            - containerPort: 3000
