apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend-hml
  namespace: igreja-hml
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`backend-hml.local`)
      kind: Rule
      services:
        - name: backend-hml
          port: 80
