apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
  namespace: igreja-dev
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`backend.local`)
      kind: Rule
      services:
        - name: backend
          port: 80
