apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend-dev-http
  namespace: igreja-dev
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`backend-dev.ministerionovotempo.app.br`)
      kind: Rule
      middlewares:
        - name: redirect-https
      services:
        - name: backend
          port: 80
