apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-dev-http
  namespace: igreja-dev
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`frontend-dev.ministerionovotempo.app.br`)
      kind: Rule
      middlewares:
        - name: redirect-https
      services:
        - name: frontend
          port: 80
